#  Template maven-build

#  This template allows you to test and build your Java project with Maven.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: pom.xml and appropriate project structure should exist in the repository.

image: maven:3.6.3

pipelines:
  default:
    - parallel:
      - step:
          name: Build and Test
          caches:
            - maven
          script:
          #CI: Build a test
            - mvn -B verify --file pom.xml
          #CD: deploy su dockerhub
            - docker image build --tag gaetanos98/ingdelsoftwareavanzata:0.1 .
            - docker login --username $dockerhub_username  --password $dockerhub_password
            - docker push gaetanos98/ingdelsoftwareavanzata
          after-script:
              # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
            - pipe: atlassian/checkstyle-report:0.3.0
          services:
            - docker 
      - step:
          name: Security Scan
          script:
            # Run a security scan for sensitive data.
            # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
            - pipe: atlassian/git-secrets-scan:0.5.1